#!/usr/bin/env ruby
require 'fileutils'

def link file
  file = File.expand_path file
  File.directory?(file) ? link_dir(file) : link_file(file)
end

def link_file file
  target = File.expand_path("~/.#{File.basename(file)}")
  File.delete(target) if File.symlink?(target) || File.exist?(target)
  File.symlink(file, target)

  puts " * Created link #{target} -> #{file}"
end

def link_dir dir
  target = File.expand_path("~/.#{File.basename(dir)}/")
  FileUtils.rm_r(target) if File.symlink?(target) || File.exist?(target)

  File.symlink(dir, target)
  puts " * Created link #{target} -> #{dir}"
end

def link_to file, target
  file = File.expand_path file
  target = File.expand_path target

  FileUtils.mkdir_p(File.dirname(target))
  File.delete(target) if File.symlink?(target) || File.exist?(target)
  File.symlink(file, target)

  puts " * Created link #{target} -> #{file}"
end

Dir.chdir(File.dirname(__FILE__))
Dir["*"].sort.select{ |path| File.directory? path }.each do |directory|
  install_script = "#{directory}/install"
  load(install_script) if File.exist? install_script
end
