#!/usr/bin/env ruby

Dir.mkdir "~/.vim/bundle"
`git clone git@github.com:Shougo/neobundle.vim.git ~/.vim/bundle/neobundle.vim` unless File.exists?(File.expand_path("~/.vim/bundle/neobundle.vim"))
%w[vimrc gvimrc .].map { |rc| link("vim/#{rc}") }
