# Path to oh-my-zsh installation.
export ZSH=/Users/chrisnix/.oh-my-zsh

# react native android
export ANDROID_HOME=/Users/chrisnix/Library/Android/sdk/
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

# RVM
export PATH="$PATH:$HOME/.rvm/bin"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Theme
ZSH_THEME="spaceship"

# Plugins
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Aliases
alias l="ls -hal"
alias ll="l | less"
alias rmf="rm -rf"
alias zshrc="code ~/.zshrc"
alias server='python -c "import SimpleHTTPServer;SimpleHTTPServer.test()"'
alias be='bundle exec'
alias rc='bundle exec rails c'
alias rs='bundle exec rails s'
alias mykey='cat ~/.ssh/id_rsa.pub | pbcopy'
alias ga='git add'
alias gr='git reset'
alias gst='git status'
alias gpl='git pull'
alias gps='git push'
alias gco='git checkout'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gf='git flow'
alias yolo='git push --force'
alias ya='yarn add'
alias yag='yarn add global'
alias caskupdate='brew cask list | xargs brew cask reinstall'
alias v='vim'

# Functions
# Make dir and cd into it
function mkcd {
  mkdir $1
  cd $1
}

# Rails new and cd into it
function rn {
  rails new $1 && cd $1 && git init && git add . && commit -m 'Initial commit';
}

# Start Rails Server with IP and Port
function rs {
  rails server -b ${1:-localhost} -p ${2:-3000}
}


source "/Users/chrisnix/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
